### ISSUE TITLE
script can't connect

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#20] opened 2018-09-30 22:07 UTC
> `Checking for script updates...
> 
> This script cannot connect to the Internet!
> You are either not connected or BITS does not have permission.
> If BITS does not have permission, daily automatic updates will still work.
> BITS permissions only affect updating interactively on-demand with this script.
> The Unified Hosts has not yet been marked in your local hosts file`

I don't have any virus scanner or firewall, and am running Windows 10 ENT B1803. The script can for some reason not connect to the internet while everything else on my pc connects just fine. I have also restarted the BITS service. No idea what to do, I also disabled and enabled my network adapter, but same issue still.

**Comment by ghost** [comment] 2018-09-30 22:24
I see the link it's looking for is offline (400: Invalid request) (not just for me, I asked others to confirm)
> https://raw.githubusercontent.com/ScriptTiger/Unified-Hosts-AutoUpdate/master

I suggest you add another link to the script just to check internet connection, so that it doesn't look like the script is unable to reach the internet just because one link is offline. I suggest checking EFF.org to determine internet connection so that the script knows the difference between no internet connection and the hosts url being offline.

**Comment by ScriptTiger** [comment] 2018-10-01 03:59
Thank you for trying to troubleshoot this issue on your end, it is much appreciated. However, the actual link it is using to check connectivity is the following:

https://raw.githubusercontent.com/ScriptTiger/Unified-Hosts-AutoUpdate/master/VERSION

The link you are talking about is only the base URL for my GitHub content, while the VERSION file is what is actually checked. The script must have access to the VERSION file in case of critical changes to the formatting of Steven Black's lists that could break the script or have otherwise undesirable results. I also use the VERSION file to push other non-critical feature updates. For safety reasons, if the VERSION file cannot be accessed, it's safer if the script does not attempt to connect to anything else. This check is made both when you run the script manually and by the system when the automatic update task is run to ensure the script runs in the safest way possible.

> If BITS does not have permission, daily automatic updates will still work.
> BITS permissions only affect updating interactively on-demand with this script.

Can you verify the script is, in fact, not connecting to the Internet during the automatic update? You can verify this by removing Unified Hosts entries entirely from your hosts file and then run the update task either by going to the Task Scheduler and manually running the `Unified Hosts AutoUpdate` task or by waiting a day and checking. When you check your hosts file, ensure the `Date:` line near the top of the file is the same as the latest hosts file from Steven Black.

For more information on this issue, please refer to https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/11. This issue has been addressed in the past. Right now the script should be able to successfully write to your hosts file the following lines:

```
#### BEGIN UNIFIED HOSTS ####
#### END UNIFIED HOSTS ####
```

It should also successfully create the `Unified Hosts AutoUpdate` task which will run with system level permissions at a later time without issue.

The current solution stated above has been acknowledged by others having the issue, as can be found in the linked issue. If the script actually can't connect at all during automatic updates, then this is actually a different issue, so please let me know what you find after following my instructions above.

I realize this may be highly confusing, as one might assume the script should update on-demand whenever you manually run it, but this is not the case for those experiencing permission problems. For those experiencing permission problems, the script simply prepares for automatic updates to be run at a later time and not while you are running the script manually.

Please also note that this script is designed to be compatible with Windows operating systems from XP on, where "Run As..." and other ways of using administrative permissions are implemented slightly differently. For operating systems newer than XP, "Run as administrator" may not actually give you the full administrative privileges you think you should have by running the task and it is not equivalent to an actual member of the "Administrators" group running the task.

Due to the confusion this has caused, I will most definitely update the readme as soon as this issue is resolved to make these points more clear. In the meantime, I look forward to getting your feedback on what I have stated above and thank you for your interest in the project!

**Comment by ghost** [comment] 2018-10-01 23:29
Thank you for the reply, not sure what is happening, because I am the only user profile on this pc, and I am the main admin. Right clicking and choosing "run as admin"worked for me when I got the script for the first time (and for about a week or two after).

Right now, choosing "run as admin" gives the error I mentioned, and only saves the following (empty list) to the hosts file:

>#### BEGIN UNIFIED HOSTS ####
>#### END UNIFIED HOSTS ####

but telling the script to make the task schedule, and then running the task manually does the job well, so I guess it works, but not the way you'd expect.

Maybe the .cmd script (or a separate one can be added to) trigger the scheduled task to run instead of running itself?
for example:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc721884(v=ws.11)

**Comment by ScriptTiger** [comment] 2018-10-02 00:37
> but telling the script to make the task schedule, and then running the task manually does the job well, so I guess it works, but not the way you'd expect.

Yeah, no worries, I really need to clean up my readme and maybe think about how to make the warning/dialog in the script itself better so people don't get worried about it. It's more of just an informational note and not really a warning since it's designed to still work.

> Maybe the .cmd script (or a separate one can be added to) trigger the scheduled task to run instead of running itself?

If you followed my instructions from above and ran the script and then manually ran the task and the task was successfully created and worked fine, it means it is already set up to run automatically every day already and there shouldn't be any need to do anything further, unless I'm mistaken about something.

**Comment by ghost** [comment] 2018-10-02 02:58
Well, the issue is when you need something immediately blocked or unblocked (custom/ignore list) and want it to update your hosts instantly so you can for example access a site that is being blocked, then you want to easily make the script update the hosts file. I personally now know to open task scheduler and run the schedule, but I'm guessing most people would prefer a more direct way of forcing update. Maybe a separate script cmd/bat that is called "force update" that checks for the schedule, (and if it's not there creates it) and then runs the schedule which runs the main script.

**Comment by ScriptTiger** [comment] 2018-10-02 05:55
I am now calling it "interactive offline mode" and I have set it up to automatically run the scheduled task after the script completes if you are in said "interactive offline mode". I have not pushed it as an update yet. Would you mind giving the new update a test before I roll it out for everyone? You can either fetch the updates with git like normal or just download the whole package here:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/archive/master.zip

Let me know what you think and, most importantly, if everything works. As long as it's an improvement and nothing is broken, I'll roll the version over so everyone else will get it as update automatically.

**Comment by ghost** [comment] 2018-10-02 10:51
Seems to work fine. I've now tested it a bunch of time.

My only remaining issue is that only changing 1 rule in ignore.txt or custom.txt and running the script to update hosts, it takes a long while before anything is updated and the ignore/custom list is updated into hosts. I'm guessing because the script is busy downloading the full StevenBlack list, but is it possible to first update changes from ignore and custom.txt and then download the new list? Because the way it is right now, you're waiting so long without any indication of anything that you think maybe the schedule is not running at all or that something has gone wrong (and are compelled to run the script again).

So maybe update hosts file based on ignore and custom immediately, and then go about the rest of the work, or maybe some indication that something is being done in the background. Maybe even add a powershell script for windows 8, 8.1 and 10 users, since[ powershell has the possibility of showing a progress bar](https://mcpmag.com/articles/2017/08/17/create-progress-bars-in-powershell.aspx), so that running the script manually can show the user that things are being worked on and that the script is actually still running.

**Comment by ScriptTiger** [comment] 2018-10-02 11:57
Due to project compatibility goals, this script steers away from making PowerShell a requirement. If I was to add anything that required PowerShell, there would be no reason why then the entire script would not be in PowerShell, which could do many of the operations far more efficiently. After further development of the current script, translating it to a PowerShell script later in a different repo would be the better approach. However, this script will still remain the primary development script as it offers maximum compatibility and should serve as the model for any child projects.

As far as showing progress, there are many different ways to show progress just within the standard environment without the need to incorporate things like PowerShell. I'll make a reference to https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/3 here since this is more of a UI issue so I don't forget. I have been toying with several different UI ideas, but I'd like to get the more critical discrepancies worked out first before cluttering up the program flow with non-critical features.

I'll close this issue since you have confirmed the fix for your title issue, but, as I said, I have referenced https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/3 here to keep the **hosts file write operation progress output feature request** (Note to self) on my to-do list in that issue. Thanks again for the feedback and keep it coming if you've got it!

**Closed as completed by ScriptTiger** 2018-10-02 11:57 UTC

**Comment by ScriptTiger** [comment] 2018-10-03 05:18
@horusra, I know I closed this, but there was still a lot of related work left unfinished even after I fixed your specific issue. Can you run your script again and check out the new features and let me know your feedback and if it works/breaks?

Some things I have added are:
- The ability to run the script with the sole purposes of activating the scheduled task
- The ability to overwrite your current scheduled task with a new one if you run the script and already have a task set up
- A bit more progress on the scheduled task being completed
- I tried to simplify the BITS permission info so it doesn't sound like anything is wrong because I don't want users to be unnecessarily worried, as it can still run perfectly fine in the new interactive offline mode (or should run perfectly fine, pending your testing)

Thanks again for all your help so far! After implementing BITS, I knew there were going to be some problems, but I think you have really helped me to drastically diminish the remaining issues that might exist.
