### ISSUE TITLE
Compression Level

### ISSUE THREAD

**Issue by Bennibaba** [ScriptTiger/Unified-Hosts-AutoUpdate#23] opened 2019-03-19 04:30 UTC
Hello,

thank you very much for the amazing script.
Could you tell me more about the compression? What excactly is the advantage to use a highter or lower level?

I am talking about this part:
`	echo Your hosts file can be from 1 to 9 domains per line.
	echo 1 is standard, more than 1 is a level of compression.
	echo If you choose a level of compression, please expect the update to take longer.
	echo Your current compression level is %OLDCOMP%.
	choice.exe /m "Would you like to just stick with that?"`

Thank you very much

**Comment by ScriptTiger** [comment] 2019-03-19 04:47
Its advantages and disadvantages are varied across systems, but basically it comes down to some Windows platforms have issues staging hosts files with larger line counts. Some Windows platforms have this issue and some don't, the causes are not fully understood or documented, so I apologize for that. However, I am always actively researching this myself, as well, and if you can find anything new as far as the exact cause or documentation to that effect, I'm sure we would all be very much appreciative.

Both this repo as well as Steven Black's repo have various issues related to this topic. The cause is not clear, the symptoms are varied, but the solution is usually always compression when it comes to a Windows system having issues.

To review prior issues related to compression, before and after its implementation, you can check out this quick search link:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues?utf8=%E2%9C%93&q=compression

And another search link for Steven Black's repo, which we collaborate closely with:
https://github.com/StevenBlack/hosts/issues?utf8=%E2%9C%93&q=compression

**Comment by ScriptTiger** [comment] 2019-10-09 05:46
I had this issue open just as a reference for others because it is a popular talking point, but I'll close it now and just keep it pinned to the issue page instead so people can still use it as a quick reference.

**Closed as completed by ScriptTiger** 2019-10-09 05:46 UTC
Labels: question
