### ISSUE TITLE
Missing an argument for parameter

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#28] opened 2019-06-16 22:30 UTC
![image](https://user-images.githubusercontent.com/17074394/59570340-fae02b00-9096-11e9-8130-1417135959e2.png)
not sure why this error shows up

**Comment by ScriptTiger** [comment] 2019-06-16 23:37
Does the script still work as intended, despite the error? The script comes with several defaults and workarounds to still be able to function in the event of several errors such as that. This is only a problem if your script is not successfully updating your hosts file as intended.

If you can confirm the script still works as intended, despite the error, I can simply prevent such error output from displaying in the future to prevent confusion.

**Comment by ghost** [comment] 2019-06-17 16:08
the script still works, but I would not hide the error, instead just add before it that some errors might show up but the script might still work.

**Comment by ScriptTiger** [comment] 2019-06-18 01:14
No, I completely agree, errors should not be hidden, but rather handled. But due to the wide range of systems this script targets, it's impossible for me to account for and handle all of the possible errors beforehand. This is why I employ multiple safeguards to prevent unforeseeable circumstances and ensure the safest experience possible. Also, thanks to feedback like yours, I can account for and handle each error one by one as user feedback permits. So I do greatly appreciate your feedback, as well as others who have contributed in the past, and encourage others to also let me know of any issues they find, as well.

I have addressed this specific issue in version 1.24. And as I say above, the error is not hidden, but rather handled. If an error arises with BITS, you will still get an error displayed. That was also a very valid concern on your part, so no worries there. Let me know if the new update works for you, and if so you can close the issue. Thanks, again, for your feedback, it's always most welcome!

**Comment by ScriptTiger** [comment] 2019-06-24 09:15
I'll close this issue for now, but feel free to follow-up later with any comments. Thanks, again!

**Closed as completed by ScriptTiger** 2019-06-24 09:15 UTC
