### ISSUE TITLE
Port to PowerShell

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#37] opened 2020-01-03 10:16 UTC
The script works great, but really PowerShell would be a much, much better options in any way imaginable (first and foremost ease of maintenance for you). The current ~700 lines would probably be cut in half, while making it more robust.

**Comment by ScriptTiger** [comment] 2020-01-03 10:41
I think a couple people have already made PowerShell scripts. @grantcarthew? I intentionally maintain this project as the default CLI interpreter because the environments I personally have experience with, namely government systems requiring a certain level of hardening, have restrictions against PowerShell. Also Windows Server 2008/Windows Vista and earlier systems don't come with PowerShell, so it would not work out of the box for those systems. This script is more geared towards security-minded people that don't want to download extra unnecessary components, etc.

**Comment by ohadschn** [comment] 2020-01-03 11:50
PS restrictions are easy, all you have to do is run `powershell -ExecutionPolicy Unrestricted` from your batch script. Security has nothing to do with this, you could write malware in batch if wanted to (you are already calling external executables so calling `virus.exe` is basically the same).

As for Vista, extended support ended almost 3 years ago - this means no updates, including security updated. So the secure thing to do is not support it. It also comes with Vista SP1 which a security conscious setup would have installed. Same for Win 2008, extended support will end in 10 days, and it's included since R2.

Everyone, including MS itself, is using PS these days. Losing out on its countless benefits for some extreme (possibly theoretical) minority, is unwise IMO. Especially when done in the name of security, which it can't be secure (extended support ended).

**Comment by ScriptTiger** [comment] 2020-01-03 12:16
I understand where you are coming from, but government programs of record are not maintained like that. And when you get into closed-network systems with a certain level of security clearance, it just becomes more of a headache. Plenty of internal warehouse systems are still running Windows 4.0. Why then would such closed-network systems need something to maintain a hosts file to block domains on the open Internet? Well, there are also transient systems running programs of record that often move between networks.

Obviously I entirely agree with you about the need for staying up to date and relevant with security updates, however who has been getting hit hardest by the majority of ransomware attacks? Government and corporate systems locked into programs of record. That is just a fact, neither theoretical nor minority. There are other PowerShell scripts out there to cover everything that you're saying, but that's just not the use case this particular script was designed for. And even if I was to make a PowerShell script, it would obviously be a completely different language and completely different repository to this one, so discussing it is a bit out of scope here.

Again, I agree with everything you are saying, it just comes down to this script has a separate and clearly defined use case which that falls outside of. It's like posting an issue on Ubuntu asking them to change to Fedora.

**Comment by ohadschn** [comment] 2020-01-03 12:50
OK, so I would return to the priority argument. IMHO your time would be spent far more efficiently on a PS solution, rather than work hard to create, maintain, and improve a batch script whose necessity is extremely rare, and at this point theoretical. In the other issues you started a discussion with your users, how about we do the same here? I'm willing to bet not a single user would object to a PowerShell migration (be it here or on a different repo, suspending this one's maintenance).

**Comment by ScriptTiger** [comment] 2020-01-03 14:18
You know, to be honest I'll make another point for my case, as well, that I didn't think of before. You're working for Microsoft, but in my case I work for myself and handle all of my own business through independent contracts and the like. Obviously ScriptTiger is one personal silo, as I don't like misrepresenting certain other entities. But to be honest I really just make products for myself and my problems that I have experience with. Trying to guess at someone else's problems and making products for them diminishes both quality and impact. I then use constructive user feedback, like yours, to improve upon my work and everybody benefits, hopefully.

For this particular project it just so happens a lot of people outside the scope of the ideal audience, let's say,  are able to use it due to the near zero prerequisites needed as well as are happy using it because it's easy to use and as fault tolerant as I could possibly make it. It's really just a coincidence that people that could be using better products prefer to use mine even though their system has the potential to run more powerful script engines. There are always going to be bigger and better things out there in some way, but I stick to my principles in that way and don't go chasing rainbows, as TLC once said.

All that being said, the PowerShell issue has been brought to my door before, I'm assuming because my script works better than the current PowerShell scripts out there and they think it would be a lot more awesome if I just ported it over. I won't disagree with that and I am flattered in a way that requests like this keep coming in. However, I just haven't had the time to start another project. I still have a project for @spirillen that's been sitting in my queue a good long while now that has first priority whenever I can steal some time away. @spirillen, I'm still alive and I know you're tapping your foot over the hosts file conversion scripts for Unbound DNS RPZ, I still remember :P

**Comment by ScriptTiger** [comment] 2020-01-03 15:38
I'm going to close this one as it's ultimately out of scope and giving me an itch to unnecessarily strafe. All these dang kids coming in here with their newfangled ideas and trying to break an old man set in his ways from what he's always done. LOL, that's what I feel like anyway when I read my own replies.

I really do appreciate your interest and feedback though, @ohadschn, this has just been a touchy issue because it has come up multiple times not only in my repositories but also over in @StevenBlack's. So if I have made any undue comments towards you, my apologies.

If it makes you feel any better, Steven did have a cow at me over strafing DNS visionary Paul Vixie when he stopped by asking for some RPZ conversions. I won't link it or mention him because it's embarrassing in retrospect, but you can search it if you really want to. In the end I was able to help him though and he now follows me on Twitter, along with an exclusive group of 176 other people, which is actually pretty touching when you think about who the man actually is and what he has done. So although I admittedly may be annoying at times, I do try to do the right thing and mean well, although maybe it could be construed as egocentric by saying that about one's self.

**Closed as completed by ScriptTiger** 2020-01-03 15:38 UTC

**Comment by ohadschn** [comment] 2020-01-03 18:12
In my book, a person freely contributing his time and energy for the good of the public like you do here would never be considered egocentric. An you kept the discussion strictly professional, all comments were fair and due :)

Really this suggestion was mostly to make life easier for you (you have no idea how better your life will be with PS), but if that's your cup of tea it's totally cool - script works perfectly as is (missing alert on failure would be my only true gripe). 

If it's any consolation, I've been programming in one form or another for about 30 years, so you're not the only old guy around...

**Comment by ohadschn** [comment] 2020-01-03 18:21
BTW one thing I don't get, I do see you reference `powershell` in your script, so aren't you already dependent on it? https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/ef058531be81066f8205a0e3f2c3a780901168cb/Hosts_Update.cmd#L66

Or do you have some logic that works around it if it's unavailable?

**Comment by ScriptTiger** [comment] 2020-01-03 18:41
> Or do you have some logic that works around it if it's unavailable?

There is indeed, BITS does work without PowerShell. However, I have PowerShell handle it by default if it is available because there are obviously several advantages to that and downloading the files properly is critically key to the entire script's function.

`powershell get-bitstransfer > nul && set /a BITS=%BITS%+2`
 
The line you referenced is just a check to see if BITS is available through PowerShell or not.

`bitsadmin /list > nul && set /a BITS=%BITS%+1`

The line above the line you referenced is a check to see if BITS is available at all.

If BITS is available but it cannot be accessed through PowerShell, it is instead accessed directly using `bitsadmin /transfer`. BITS is the only thing that older systems are required to install in order for the script to function, otherwise modern systems all come with it and this will never be an issue for most people. Since even the closed-network systems I've worked on have WSUS and update distribution, BITS is usually bundled along with that for security allowances, so it shouldn't pose much administrative overhead either for trying to build a case to make an individual exception for it.

**Comment by spirillen** [comment] 2020-01-03 20:33
A little OT but let's have the Friday :beers: :smiley: 

> I'm still alive and I know you're tapping your foot over the hosts file conversion scripts for Unbound DNS RPZ, I still remember :P

Don't worry, it's your spare time you using and as such no deadlines. And no toes, fingers or feet are tapping, as I'm a terrible dancer :rofl: 

> you have no idea how better your life will be with PS

Hmm, @ohadschn have you tried something called bash (linux), you know open source with no built in spyware? :rofl: It also mostly default comes with some weird weird opensource program called python :beers: 

#### side note to the :arrow_up: 
I haven't used any windows since XP, which was the last somehow decent windows OS.

**Comment by ohadschn** [comment] 2020-01-03 22:56
PowerShell is actually open source and cross-platform these days, I really recommend you check it out!
https://github.com/PowerShell/PowerShell

**Comment by spirillen** [comment] 2020-01-03 23:07
I'm 100% sure I won't :smile: 

Don't worry Micro\*bliip\* is off limit after XP and have no access on my network, to much Trump there and they chances for regaining any trust is less than indifferently -0

Mostly I'm sorry you misunderstood my Friday :beers: as a invitation to promote this. I was hoping for a smile for the *nix vs proletarian software

**Comment by grantcarthew** [comment] 2020-01-04 02:13
Hi guys,

I was pinged above so I am commenting.

I have a [script](https://github.com/grantcarthew/ps-gcpowershell/blob/master/GCHostsFile/Install-GCHostsFileBlockList.ps1) that installs the block list into the hosts file.

The module has been published on the [PowerShell Gallery](https://www.powershellgallery.com/packages/GCHostsFile/0.3).

I haven't used it for a while because I now run Debian Sid on my laptop and I don't use it at work.

If you are interested in becoming a contributor, happy to add you in. You could just fork it.

Happy new year guys.

**Comment by ScriptTiger** [comment] 2020-01-04 02:35
Thanks, @grantcarthew, for the reply! I knew you had participated in at least a couple different conversations about some PowerShell projects. I won't be able to contribute any time soon due to my current workflow, but @ohadschn might be interested in checking it out. Just get ready to take a lot of new issues, he's quite a talker :P Although if you're not using the script yourself anymore and also recommending I fork it, I'll assume that to mean you're no longer actively developing it either.
